name: aicms_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  intl: ^0.20.2
  file_picker: ^9.1.0
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  shared_preferences: ^2.0.8
  collection: ^1.18.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
